/* InflatePro Customs Pro V2 — local front-end business catalog */
const STARTER_PRODUCTS=[
{id:1,name:"Fast Food Character Inflatable",category:"Franchise",market:"Restaurants",use:"Brand Display",price:10000,emoji:"🍔",rating:4.9,reviews:42,badge:"Popular",size:"Up to 6 ft",productionDays:45,water:false,newest:25,desc:"Custom restaurant character inflatable for franchises, grand openings, drive-thru promotions, and photo moments.",tags:["Character","Franchise","Logo Ready","Photo Spot"],keywords:["mcdonalds","burger","restaurant","fast food","character"],images:[]},
{id:2,name:"Restaurant Mascot Inflatable",category:"Franchise",market:"Restaurants",use:"Photo Spot",price:8500,emoji:"🐼",rating:4.8,reviews:31,badge:"Custom",size:"4-8 ft",productionDays:45,water:false,newest:24,desc:"Standing or sitting mascot inflatable designed for restaurants, food brands, and retail chains.",tags:["Mascot","Custom Pose","Indoor/Outdoor"],keywords:["panda","restaurant","mascot","brand"],images:[]},
{id:3,name:"College Mascot Inflatable",category:"College",market:"Schools",use:"School Event",price:9000,emoji:"🏈",rating:4.9,reviews:26,badge:"School",size:"5-10 ft",productionDays:50,water:false,newest:23,desc:"School mascot inflatable for games, tailgates, student events, alumni activities, and campus photo areas.",tags:["College","Mascot","Tailgate"],keywords:["school","college","byu","utah","football","mascot"],images:[]},
{id:4,name:"Branded Entrance Arch",category:"Promotional",market:"Events",use:"Brand Display",price:4200,emoji:"🎪",rating:4.7,reviews:54,badge:"Best Value",size:"10-30 ft wide",productionDays:35,water:false,newest:22,desc:"Large inflatable arch for entrances, races, school events, store openings, and sponsor displays.",tags:["Arch","Logo","Entrance"],keywords:["arch","entrance","race","sponsor"],images:[]},
{id:5,name:"King of the Hill Inflatable",category:"Activity",market:"Event Rentals",use:"Game / Activity",price:12000,emoji:"⛰️",rating:4.8,reviews:19,badge:"Premium",size:"Custom",productionDays:60,water:true,newest:21,desc:"Competitive climbing inflatable with ramps, ropes, soap/water use, and padded landing zones.",tags:["Activity","Teen/Adult","Climbing","Water Option"],keywords:["king of the mountain","hill","climb","water","soap","teen"],images:[]},
{id:6,name:"Slip and Slide Track",category:"Water",market:"Event Rentals",use:"Water Attraction",price:7500,emoji:"🌊",rating:4.6,reviews:38,badge:"Summer",size:"30-100 ft",productionDays:50,water:true,newest:20,desc:"Long inflatable water track with raised side walls, slick surface, and custom color combinations.",tags:["Water","Summer","Custom Length"],keywords:["slip n slide","slip and slide","water slide","summer"],images:[]},
{id:7,name:"Inflatable Bowling Slide",category:"Activity",market:"Event Rentals",use:"Game / Activity",price:6800,emoji:"🎳",rating:4.8,reviews:22,badge:"Fun",size:"25-60 ft",productionDays:45,water:true,newest:19,desc:"Players slide down a slick inflatable lane and crash into oversized bowling pins.",tags:["Game","Bowling","Water Option"],keywords:["bowling","pins","slide","game"],images:[]},
{id:8,name:"Oversized Product Replica",category:"Retail",market:"Retail Brands",use:"Photo Spot",price:6000,emoji:"🥤",rating:4.9,reviews:44,badge:"Photo",size:"Custom",productionDays:50,water:false,newest:18,desc:"Giant inflatable version of a product, package, drink, food item, bottle, or box.",tags:["Retail","Product Launch","Photo Spot"],keywords:["product","replica","giant","bottle","cup"],images:[]},
{id:9,name:"Giant Logo Display",category:"Promotional",market:"Corporate",use:"Brand Display",price:3800,emoji:"🔵",rating:4.7,reviews:61,badge:"Logo",size:"Custom",productionDays:35,water:false,newest:17,desc:"Large inflatable logo display for storefronts, trade shows, events, and corporate activations.",tags:["Logo","Trade Show","Brand"],keywords:["logo","display","trade show","corporate"],images:[]},
{id:10,name:"College Team Tunnel",category:"College",market:"Schools",use:"School Event",price:14000,emoji:"🏟️",rating:4.9,reviews:18,badge:"Premium",size:"Custom",productionDays:65,water:false,newest:16,desc:"Inflatable team entrance tunnel for games, player introductions, pep rallies, and spirit events.",tags:["Sports","Tunnel","School"],keywords:["tunnel","team","football","entrance"],images:[]},
{id:11,name:"Inflatable Photo Chair",category:"Promotional",market:"Retail Brands",use:"Photo Spot",price:3200,emoji:"🪑",rating:4.5,reviews:29,badge:"Low Cost",size:"6-12 ft",productionDays:35,water:false,newest:15,desc:"Oversized branded inflatable chair made for social media photos and event attention.",tags:["Photo","Social Media","Brand"],keywords:["chair","photo","instagram","social"],images:[]},
{id:12,name:"Interactive Water Climb",category:"Water",market:"Event Rentals",use:"Water Attraction",price:11500,emoji:"🧗",rating:4.8,reviews:16,badge:"Water",size:"Custom",productionDays:60,water:true,newest:14,desc:"Water-friendly climbing attraction with ropes, slides, and soft landing areas.",tags:["Water","Climb","Activity"],keywords:["water","climb","rope","slide"],images:[]},
{id:13,name:"Mascot Head Entrance",category:"College",market:"Schools",use:"School Event",price:12500,emoji:"🦁",rating:4.7,reviews:12,badge:"School",size:"Custom",productionDays:60,water:false,newest:13,desc:"Walk-through mascot head entrance for schools, sports teams, and fan experiences.",tags:["Mascot","Entrance","School"],keywords:["head","entrance","lion","mascot"],images:[]},
{id:14,name:"Basketball Dunk Challenge",category:"Sports",market:"Events",use:"Game / Activity",price:7200,emoji:"🏀",rating:4.6,reviews:35,badge:"Sports",size:"Custom",productionDays:45,water:false,newest:12,desc:"Branded basketball-style inflatable game for corporate, school, and sports events.",tags:["Sports","Game","Branded"],keywords:["basketball","dunk","sports","game"],images:[]},
{id:15,name:"Giant Food Display",category:"Franchise",market:"Restaurants",use:"Photo Spot",price:5800,emoji:"🍟",rating:4.8,reviews:47,badge:"Food",size:"Custom",productionDays:45,water:false,newest:11,desc:"Oversized inflatable food item for restaurants, food festivals, openings, and campaigns.",tags:["Food","Restaurant","Photo"],keywords:["fries","food","restaurant","giant"],images:[]},
{id:16,name:"Retail Sale Inflatable",category:"Retail",market:"Retail Brands",use:"Brand Display",price:2900,emoji:"🏷️",rating:4.4,reviews:73,badge:"Deal",size:"Custom",productionDays:30,water:false,newest:10,desc:"Storefront promotional inflatable for sales, grand openings, and traffic attention.",tags:["Retail","Sale","Storefront"],keywords:["sale","retail","store"],images:[]},
{id:17,name:"Corporate Event Dome",category:"Promotional",market:"Corporate",use:"Brand Display",price:15500,emoji:"🏕️",rating:4.9,reviews:11,badge:"Premium",size:"Custom",productionDays:70,water:false,newest:9,desc:"Branded inflatable dome for corporate activations, trade shows, and large events.",tags:["Corporate","Event","Premium"],keywords:["dome","corporate","activation"],images:[]},
{id:18,name:"Inflatable Obstacle Lane",category:"Activity",market:"Event Rentals",use:"Game / Activity",price:13200,emoji:"🏃",rating:4.7,reviews:23,badge:"Large",size:"40-100 ft",productionDays:65,water:false,newest:8,desc:"Custom obstacle attraction with brand colors, sponsor panels, and event-friendly layout.",tags:["Obstacle","Activity","Event"],keywords:["obstacle","course","lane","activity"],images:[]},
{id:19,name:"Water Bowling Lane",category:"Water",market:"Event Rentals",use:"Water Attraction",price:7900,emoji:"💦",rating:4.6,reviews:20,badge:"Water",size:"30-70 ft",productionDays:50,water:true,newest:7,desc:"Water-based bowling lane with slide surface, splash zone, and oversized pins.",tags:["Water","Game","Bowling"],keywords:["water bowling","splash","pins"],images:[]},
{id:20,name:"Giant Shoe Replica",category:"Retail",market:"Retail Brands",use:"Photo Spot",price:6500,emoji:"👟",rating:4.5,reviews:14,badge:"Retail",size:"Custom",productionDays:50,water:false,newest:6,desc:"Oversized inflatable shoe for sports stores, shoe launches, and brand events.",tags:["Retail","Sports","Product"],keywords:["shoe","sneaker","sports","replica"],images:[]},
{id:21,name:"Pop-Up Brand Wall",category:"Promotional",market:"Corporate",use:"Photo Spot",price:3600,emoji:"📸",rating:4.5,reviews:57,badge:"Photo",size:"Custom",productionDays:35,water:false,newest:5,desc:"Inflatable backdrop wall for logos, sponsors, photo booths, and trade shows.",tags:["Backdrop","Sponsor","Photo"],keywords:["wall","backdrop","photo","sponsor"],images:[]},
{id:22,name:"Sports Mascot Tunnel",category:"Sports",market:"Schools",use:"School Event",price:14500,emoji:"🐯",rating:4.8,reviews:13,badge:"Sports",size:"Custom",productionDays:65,water:false,newest:4,desc:"Custom sports entrance tunnel with mascot face, colors, and team branding.",tags:["Sports","Mascot","Tunnel"],keywords:["sports","tunnel","mascot","team"],images:[]},
{id:23,name:"Restaurant Roof Display",category:"Franchise",market:"Restaurants",use:"Brand Display",price:8200,emoji:"🍕",rating:4.7,reviews:25,badge:"Outdoor",size:"Custom",productionDays:50,water:false,newest:3,desc:"Large inflatable display built for restaurant rooftops, entrances, or parking lot promotions.",tags:["Restaurant","Display","Brand"],keywords:["roof","restaurant","pizza","outdoor"],images:[]},
{id:24,name:"Inflatable Stage Frame",category:"Promotional",market:"Events",use:"Brand Display",price:10500,emoji:"🎤",rating:4.7,reviews:17,badge:"Event",size:"Custom",productionDays:60,water:false,newest:2,desc:"Inflatable branded stage frame for events, concerts, sponsors, and announcements.",tags:["Stage","Event","Sponsor"],keywords:["stage","concert","frame"],images:[]},
{id:25,name:"Custom Character Duo",category:"Franchise",market:"Restaurants",use:"Photo Spot",price:18000,emoji:"👥",rating:4.9,reviews:8,badge:"Bundle",size:"Custom",productionDays:75,water:false,newest:1,desc:"Two matching branded character inflatables for franchises, campaigns, or location rollouts.",tags:["Pair","Characters","Campaign"],keywords:["duo","pair","characters","bundle"],images:[]}
];
const DEFAULT_CATEGORIES=["Franchise","College","Promotional","Activity","Water","Sports","Retail"];
const DEFAULT_MARKETS=["Restaurants","Schools","Events","Corporate","Retail Brands","Event Rentals"];
const DEFAULT_USES=["Brand Display","Photo Spot","Game / Activity","Water Attraction","School Event"];
const DB={products:"inflatepro_products_v3",quote:"inflatepro_quote_v3",requests:"inflatepro_requests_v3",wishes:"inflatepro_wishes_v3",compare:"inflatepro_compare_v3",recent:"inflatepro_recent_v3",categories:"inflatepro_categories_v3",leads:"inflatepro_leads_v3",builder:"inflatepro_builder_v3",admin:"inflatepro_admin_logged_in_v3"};
const app={
products:[],quote:[],wishes:[],compare:[],recent:[],categories:[],currentView:"grid",adminTab:"requests",isAdmin:false,editingProductId:null,
init(){
this.products=this.load(DB.products,STARTER_PRODUCTS);this.quote=this.load(DB.quote,[]);this.wishes=this.load(DB.wishes,[]);this.compare=this.load(DB.compare,[]);this.recent=this.load(DB.recent,[]);this.categories=this.load(DB.categories,DEFAULT_CATEGORIES);this.isAdmin=sessionStorage.getItem(DB.admin)==="true";
this.bind();this.buildFilters();this.renderDepartments();this.renderQuickMarkets();this.renderProducts();this.renderQuote();this.renderAdmin();this.renderRecentStrip();this.updateCounts();this.restoreBuilder();setTimeout(()=>this.maybeShowLeadPopup(),2500);
},
load(k,f){try{let r=localStorage.getItem(k);return r?JSON.parse(r):JSON.parse(JSON.stringify(f))}catch(e){return JSON.parse(JSON.stringify(f))}},
save(k,v){localStorage.setItem(k,JSON.stringify(v))},
bind(){
["globalSearch","globalDepartment","filterCategory","filterMarket","filterUse","filterWater","filterMin","filterMax","filterSpeed","filterRating","sortSelect"].forEach(id=>{let el=document.getElementById(id);if(el)el.addEventListener(el.tagName==="INPUT"?"input":"change",()=>this.renderProducts())});
document.getElementById("searchBtn").addEventListener("click",()=>this.renderProducts());document.getElementById("quoteForm").addEventListener("submit",e=>this.submitQuote(e));
},
unique(field){return[...new Set(this.products.map(p=>p[field]).filter(Boolean))].sort()},
fillSelect(id,first,values){let el=document.getElementById(id);el.innerHTML=`<option value="all">${first}</option>`+values.map(v=>`<option value="${this.escape(v)}">${this.escape(v)}</option>`).join("")},
buildFilters(){this.fillSelect("filterCategory","All Categories",this.categories);this.fillSelect("filterMarket","All Customer Types",this.unique("market"));this.fillSelect("filterUse","All Use Cases",this.unique("use"));this.fillSelect("globalDepartment","All",this.categories)},
renderDepartments(){document.getElementById("departmentNav").innerHTML=["All",...this.categories,"Restaurants","Schools","Admin"].map(d=>`<button onclick="app.quickDepartment('${this.escape(d)}')">${this.escape(d)}</button>`).join("")},
renderQuickMarkets(){document.getElementById("quickMarkets").innerHTML=DEFAULT_MARKETS.map(m=>`<button onclick="app.applyMarket('${this.escape(m)}')">${this.marketIcon(m)} ${this.escape(m)}</button>`).join("")},
marketIcon(m){return{Restaurants:"🍔",Schools:"🎓","Retail Brands":"🛍️",Corporate:"🏢","Event Rentals":"🎪",Events:"🎤"}[m]||"🎈"},
quickDepartment(d){if(d==="Admin"){this.showLogin();document.getElementById("adminSection").scrollIntoView({behavior:"smooth"});return}if(d==="All"){document.getElementById("globalDepartment").value="all";document.getElementById("filterCategory").value="all";document.getElementById("filterMarket").value="all"}else if(["Restaurants","Schools"].includes(d)){document.getElementById("filterMarket").value=d}else{document.getElementById("globalDepartment").value=d;document.getElementById("filterCategory").value=d}this.scrollToProducts();this.renderProducts()},
applyMarket(m){document.getElementById("filterMarket").value=m;this.scrollToProducts();this.renderProducts()},
expandSearch(q){const synonyms={panda:["mascot","restaurant","character"],mcdonalds:["fast food","restaurant","character","burger"],college:["school","sports","mascot","tunnel"],football:["college","sports","tunnel","school"],slide:["water","slip","track"],slip:["water","slide","track"],clean:["retail","display"],logo:["brand","display","promotional"],restaurant:["franchise","food","character"],basketball:["sports","game","dunk"]};let words=q.toLowerCase().split(/\s+/).filter(Boolean);let expanded=[...words];words.forEach(w=>{if(synonyms[w])expanded.push(...synonyms[w])});return expanded},
getFilteredProducts(){
const search=document.getElementById("globalSearch").value.toLowerCase().trim(),terms=this.expandSearch(search),dept=document.getElementById("globalDepartment").value,cat=document.getElementById("filterCategory").value,market=document.getElementById("filterMarket").value,use=document.getElementById("filterUse").value,water=document.getElementById("filterWater").value,min=Number(document.getElementById("filterMin").value||0),max=Number(document.getElementById("filterMax").value||999999),speed=document.getElementById("filterSpeed").value,rating=document.getElementById("filterRating").value,sort=document.getElementById("sortSelect").value;
let list=this.products.filter(p=>{let blob=[p.name,p.category,p.market,p.use,p.desc,(p.tags||[]).join(" "),(p.keywords||[]).join(" "),p.badge,p.size].join(" ").toLowerCase();let searchOk=!terms.length||terms.some(t=>blob.includes(t));let speedOk=true;if(speed==="fast")speedOk=p.productionDays<=35;if(speed==="standard")speedOk=p.productionDays>35&&p.productionDays<=55;if(speed==="long")speedOk=p.productionDays>55;return searchOk&&(dept==="all"||p.category===dept)&&(cat==="all"||p.category===cat)&&(market==="all"||p.market===market)&&(use==="all"||p.use===use)&&(water==="all"||String(p.water)===water)&&p.price>=min&&p.price<=max&&speedOk&&(rating==="all"||p.rating>=Number(rating))});
if(sort==="priceLow")list.sort((a,b)=>a.price-b.price);if(sort==="priceHigh")list.sort((a,b)=>b.price-a.price);if(sort==="rating")list.sort((a,b)=>b.rating-a.rating);if(sort==="reviews")list.sort((a,b)=>b.reviews-a.reviews);if(sort==="name")list.sort((a,b)=>a.name.localeCompare(b.name));if(sort==="newest")list.sort((a,b)=>b.newest-a.newest);return list},
renderProducts(){
const list=this.getFilteredProducts(),grid=document.getElementById("productGrid"),empty=document.getElementById("emptyState");document.getElementById("resultsTitle").textContent=`${list.length} Product${list.length===1?"":"s"} Found`;document.getElementById("resultsSubtitle").textContent=list.length?"Showing custom inflatable products and quote-ready options.":"No matches found.";this.renderFilterChips();
if(!list.length){grid.innerHTML="";empty.classList.remove("hidden");return}empty.classList.add("hidden");grid.className="product-grid"+(this.currentView==="list"?" list":"");
grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image" ${this.bg(p)}><span class="badge">${this.escape(p.badge||"Custom")}</span><button class="heart" onclick="app.toggleWish(${p.id})">${this.wishes.includes(p.id)?"♥":"♡"}</button>${this.imageFallback(p)}</div><div class="product-info"><h3>${this.escape(p.name)}</h3><p>${this.escape(p.desc)}</p><div class="stars">★★★★★ ${p.rating} <span style="color:#6b7280">(${p.reviews})</span></div><div class="price">${this.money(p.price)}</div><div class="ship">Design proof before production • ${p.productionDays} day estimate</div><div class="tags">${(p.tags||[]).map(t=>`<span class="tag">${this.escape(t)}</span>`).join("")}</div><div class="card-actions three"><button class="action-btn" onclick="app.openProduct(${p.id})">Details</button><button class="action-btn" onclick="app.toggleCompare(${p.id})">${this.compare.includes(p.id)?"Added":"Compare"}</button><button class="action-btn quote" onclick="app.addToQuote(${p.id})">Add</button></div></div></article>`).join("");this.updateCounts()},
bg(p){return p.images&&p.images[0]?`style="background-image:url('${this.escapeAttr(p.images[0])}')"`:""},imageFallback(p){return p.images&&p.images[0]?"":this.escape(p.emoji||"🎈")},
renderFilterChips(){const vals=[["Search",document.getElementById("globalSearch").value],["Department",document.getElementById("globalDepartment").value],["Category",document.getElementById("filterCategory").value],["Market",document.getElementById("filterMarket").value],["Use",document.getElementById("filterUse").value],["Water",document.getElementById("filterWater").value],["Speed",document.getElementById("filterSpeed").value],["Rating",document.getElementById("filterRating").value]].filter(([k,v])=>v&&v!=="all");let min=document.getElementById("filterMin").value,max=document.getElementById("filterMax").value;if(min||max)vals.push(["Price",`${min||"0"} - ${max||"Any"}`]);document.getElementById("appliedFilters").innerHTML=vals.map(([k,v])=>`<span class="filter-chip">${this.escape(k)}: ${this.escape(v)}</span>`).join("")},
resetFilters(){["globalSearch","filterMin","filterMax"].forEach(id=>document.getElementById(id).value="");["globalDepartment","filterCategory","filterMarket","filterUse","filterWater","filterSpeed","filterRating"].forEach(id=>document.getElementById(id).value="all");document.getElementById("sortSelect").value="featured";this.renderProducts()},
toggleView(){this.currentView=this.currentView==="grid"?"list":"grid";document.getElementById("viewModeText").textContent=this.currentView==="grid"?"Grid":"List";this.renderProducts()},
openProduct(id){const p=this.products.find(x=>x.id===id);if(!p)return;this.addRecent(id);document.getElementById("modalMainImage").style.backgroundImage=p.images&&p.images[0]?`url('${this.escapeAttr(p.images[0])}')`:"";document.getElementById("modalMainImage").textContent=p.images&&p.images[0]?"":(p.emoji||"🎈");document.getElementById("modalKicker").textContent=`${p.category} • ${p.market}`;document.getElementById("modalTitle").textContent=p.name;document.getElementById("modalRating").innerHTML=`★★★★★ ${p.rating} <span style="color:#6b7280">(${p.reviews} sample reviews)</span>`;document.getElementById("modalPrice").textContent=this.money(p.price);document.getElementById("modalDesc").textContent=p.desc;document.getElementById("modalTags").innerHTML=(p.tags||[]).map(t=>`<span class="tag">${this.escape(t)}</span>`).join("");this.renderThumbs(p,"modalThumbs","modalMainImage");document.getElementById("modalSpecs").innerHTML=this.specHtml(p);document.getElementById("modalAdd").onclick=()=>this.addToQuote(id);document.getElementById("modalCompare").onclick=()=>this.toggleCompare(id);document.getElementById("modalPage").onclick=()=>this.openProductPage(id);this.renderRelated(p,"modalRelated");document.getElementById("productModal").classList.add("open");this.renderRecentStrip()},
renderThumbs(p,thumbId,mainId){let imgs=(p.images||[]).length?p.images:[null,null,null,null];document.getElementById(thumbId).innerHTML=imgs.slice(0,4).map((img,i)=>`<button class="thumb" ${img?`style="background-image:url('${this.escapeAttr(img)}')"`:""} onclick="app.setMainImage('${mainId}','${img?this.escapeAttr(img):""}','${this.escapeAttr(p.emoji||"🎈")}')">${img?"":(["📐","🎨","📦",p.emoji||"🎈"][i]||"🎈")}</button>`).join("")},
setMainImage(mainId,img,emoji){let el=document.getElementById(mainId);el.style.backgroundImage=img?`url('${img}')`:"";el.textContent=img?"":emoji},
specHtml(p){return`<div class="spec"><strong>Category</strong><span>${this.escape(p.category)}</span></div><div class="spec"><strong>Market</strong><span>${this.escape(p.market)}</span></div><div class="spec"><strong>Use Case</strong><span>${this.escape(p.use)}</span></div><div class="spec"><strong>Size</strong><span>${this.escape(p.size)}</span></div><div class="spec"><strong>Production</strong><span>${p.productionDays} day estimate</span></div><div class="spec"><strong>Water Use</strong><span>${p.water?"Available":"Dry use"}</span></div>`},
renderRelated(p,target){let rel=this.products.filter(x=>x.id!==p.id&&(x.category===p.category||x.market===p.market||x.use===p.use)).slice(0,3);document.getElementById(target).innerHTML=`<div class="related-grid">${rel.map(r=>`<button class="related-item" onclick="app.openProduct(${r.id})"><div class="rpic" ${this.bg(r)}>${this.imageFallback(r)}</div><strong>${this.escape(r.name)}</strong><br><span>${this.money(r.price)}</span></button>`).join("")}</div>`},
closeProduct(){document.getElementById("productModal").classList.remove("open")},
openProductPage(id){const p=this.products.find(x=>x.id===id);if(!p)return;this.closeProduct();this.addRecent(id);let related=this.products.filter(x=>x.id!==p.id&&(x.category===p.category||x.market===p.market)).slice(0,4);document.getElementById("productPageContent").innerHTML=`<div class="product-page"><button class="btn small" onclick="app.closeProductPage()">Close Product Page</button><div class="product-page-grid"><div><div class="page-image" id="pageMainImage" ${this.bg(p)}>${this.imageFallback(p)}</div><div class="page-gallery">${((p.images||[]).length?p.images:[null,null,null,p.emoji]).slice(0,4).map((img,i)=>`<div ${img&&String(img).startsWith("http")?`style="background-image:url('${this.escapeAttr(img)}')"`:""} onclick="app.setMainImage('pageMainImage','${img&&String(img).startsWith("http")?this.escapeAttr(img):""}','${this.escapeAttr(p.emoji||"🎈")}')">${img&&String(img).startsWith("http")?"":(img||["📐","🎨","📦"][i]||"🎈")}</div>`).join("")}</div></div><div><h2>${this.escape(p.name)}</h2><div class="stars">★★★★★ ${p.rating} (${p.reviews})</div><h3 class="price">${this.money(p.price)}</h3><p>${this.escape(p.desc)}</p><div class="tags">${(p.tags||[]).map(t=>`<span class="tag">${this.escape(t)}</span>`).join("")}</div><div class="spec-grid">${this.specHtml(p)}</div><button class="btn primary" onclick="app.addToQuote(${p.id})">Add to Quote</button><button class="btn dark" onclick="app.openDesignBuilder()">Customize This</button></div></div><div class="related-box"><h3>Related Products</h3><div class="related-grid">${related.map(r=>`<button class="related-item" onclick="app.openProductPage(${r.id})"><div class="rpic" ${this.bg(r)}>${this.imageFallback(r)}</div><strong>${this.escape(r.name)}</strong></button>`).join("")}</div></div></div>`;document.getElementById("productPageSection").scrollIntoView({behavior:"smooth"});this.renderRecentStrip()},
closeProductPage(){document.getElementById("productPageContent").innerHTML=""},
addRecent(id){this.recent=[id,...this.recent.filter(x=>x!==id)].slice(0,10);this.save(DB.recent,this.recent)},
renderRecentStrip(){let items=this.recent.map(id=>this.products.find(p=>p.id===id)).filter(Boolean);let strip=document.getElementById("recentStrip");if(!items.length){strip.classList.add("hidden");return}strip.classList.remove("hidden");document.getElementById("recentCarousel").innerHTML=items.slice(0,8).map(p=>`<button class="mini-card" onclick="app.openProduct(${p.id})"><div class="pic" ${this.bg(p)}>${this.imageFallback(p)}</div><strong>${this.escape(p.name)}</strong><br><span>${this.money(p.price)}</span></button>`).join("")},
addToQuote(id){const p=this.products.find(x=>x.id===id);if(!p)return;let ex=this.quote.find(x=>x.id===id);if(ex)ex.qty+=1;else this.quote.push({...p,qty:1});this.save(DB.quote,this.quote);this.renderQuote();this.openDrawer()},
removeFromQuote(id){this.quote=this.quote.filter(x=>x.id!==id);this.save(DB.quote,this.quote);this.renderQuote()},
setQty(id,qty){let n=Math.max(1,Number(qty)||1);this.quote=this.quote.map(x=>x.id===id?{...x,qty:n}:x);this.save(DB.quote,this.quote);this.renderQuote()},
quoteTotal(){return this.quote.reduce((s,p)=>s+p.price*(p.qty||1),0)},
renderQuote(){let drawer=document.getElementById("drawerItems"),page=document.getElementById("quotePageItems"),total=this.money(this.quoteTotal()).replace("+","+ starting");if(!this.quote.length){drawer.innerHTML="<p>Your quote list is empty.</p>";page.innerHTML="<p>No products added yet. Add products from the catalog first.</p>"}else{let html=this.quote.map(p=>`<div class="drawer-item"><strong>${this.escape(p.name)}</strong><p>${this.money(p.price)} each</p><label>Qty <input class="qty" type="number" min="1" value="${p.qty||1}" onchange="app.setQty(${p.id}, this.value)"></label><br><button class="remove" onclick="app.removeFromQuote(${p.id})">Remove</button></div>`).join("");drawer.innerHTML=html;page.innerHTML=html.replaceAll("drawer-item","summary-item")}document.getElementById("drawerTotal").textContent=total;document.getElementById("quotePageTotal").textContent=total;this.renderBuilderPreview();this.updateCounts()},
openDrawer(){document.getElementById("quoteDrawer").classList.add("open");document.getElementById("drawerBackdrop").classList.add("open")},closeDrawer(){document.getElementById("quoteDrawer").classList.remove("open");document.getElementById("drawerBackdrop").classList.remove("open")},goToQuote(){this.closeDrawer();document.getElementById("quoteSection").scrollIntoView({behavior:"smooth"})},
openDesignBuilder(){document.getElementById("designBuilderModal").classList.add("open")},closeDesignBuilder(){document.getElementById("designBuilderModal").classList.remove("open")},applyDesignBuilder(){let data={type:buildType.value,size:buildSize.value,colors:buildColors.value,logo:buildLogo.value,location:buildLocation.value,water:buildWater.value,notes:buildNotes.value};this.save(DB.builder,data);builderData.value=JSON.stringify(data);quoteDetails.value=(quoteDetails.value?quoteDetails.value+"\n\n":"")+"Design Builder:\n"+Object.entries(data).map(([k,v])=>`${k}: ${v}`).join("\n");this.renderBuilderPreview();this.closeDesignBuilder();document.getElementById("quoteSection").scrollIntoView({behavior:"smooth"})},
restoreBuilder(){let data=this.load(DB.builder,null);if(data){builderData.value=JSON.stringify(data);this.renderBuilderPreview()}},
renderBuilderPreview(){let data=this.load(DB.builder,null),box=document.getElementById("quoteBuilderPreview");if(!data){box.innerHTML="";return}box.innerHTML=`<div class="builder-preview"><strong>Design Builder Saved:</strong><br>${Object.entries(data).map(([k,v])=>`${this.escape(k)}: ${this.escape(v)}`).join("<br>")}</div>`},
calculateEstimate(){let type=estimateType.value,size=Number(estimateSize.value||1),qty=Number(estimateQty.value||1),complexity=estimateComplexity.value;base={character:5500,arch:3200,water:6500,game:6000,display:3000}[type]||4000;let mult={simple:.85,standard:1,premium:1.35}[complexity];let low=Math.round((base+(size*450))*qty*mult*.9/100)*100,high=Math.round((base+(size*650))*qty*mult*1.2/100)*100;estimateResult.innerHTML=`<h3>Estimated Range</h3><div class="estimate-number">${this.money(low).replace("+","")} - ${this.money(high)}</div><p>This is a rough estimate. Final price depends on artwork, size, material, shipping, and quantity.</p>`},
submitQuote(e){e.preventDefault();let request={id:Date.now(),name:customerName.value,company:customerCompany.value,email:customerEmail.value,phone:customerPhone.value,buyerType:buyerType.value,quantity:quoteQuantity.value,deadline:deadline.value,budget:budget.value,details:quoteDetails.value,builder:this.load(DB.builder,null),products:this.quote.map(p=>({id:p.id,name:p.name,qty:p.qty||1,price:p.price})),total:this.quoteTotal(),status:"New",date:new Date().toLocaleString()};let requests=this.load(DB.requests,[]);requests.push(request);this.save(DB.requests,requests);alert("Quote request saved. View it in the Admin Dashboard.");this.quote=[];this.save(DB.quote,this.quote);this.save(DB.builder,null);e.target.reset();this.renderQuote();this.renderAdmin()},
printQuote(){window.print()},
showLogin(){if(this.isAdmin){document.getElementById("adminSection").scrollIntoView({behavior:"smooth"});return}document.getElementById("loginModal").classList.add("open")},closeLogin(){document.getElementById("loginModal").classList.remove("open")},login(){if(adminPassword.value==="admin123"){this.isAdmin=true;sessionStorage.setItem(DB.admin,"true");adminPassword.value="";this.closeLogin();this.updateCounts();this.renderAdmin();document.getElementById("adminSection").scrollIntoView({behavior:"smooth"})}else alert("Wrong password. Demo password is admin123.")},
renderAdmin(){let panel=document.getElementById("adminPanel");if(!this.isAdmin){panel.innerHTML=`<h3>Admin Locked</h3><p>Login to manage products, categories, quote requests, statuses, CSV export, and product galleries.</p><br><button class="btn primary" onclick="app.showLogin()">Login</button>`;return}panel.innerHTML=this.adminTab==="products"?this.productAdminHtml():this.adminTab==="categories"?this.categoryAdminHtml():this.requestsAdminHtml()},
setAdminTab(tab){this.adminTab=tab;this.renderAdmin()},
requestsAdminHtml(){let requests=this.load(DB.requests,[]);if(!requests.length)return`<p>No quote requests saved yet.</p>`;return`<div style="margin-bottom:15px;display:flex;gap:8px;flex-wrap:wrap"><button class="btn small dark" onclick="app.clearRequests()">Clear Requests</button></div>${requests.slice().reverse().map(r=>`<div class="request-card"><strong>${this.escape(r.company)} — ${this.escape(r.name)}</strong><p>${this.escape(r.email)} | ${this.escape(r.phone)} | ${this.escape(r.date)}</p><p><strong>Status:</strong> <select class="status-select" onchange="app.updateRequestStatus(${r.id}, this.value)">${["New","Contacted","Design Sent","Waiting Approval","Approved","Production","Shipped","Complete","Lost"].map(s=>`<option ${r.status===s?"selected":""}>${s}</option>`).join("")}</select></p><p><strong>Buyer:</strong> ${this.escape(r.buyerType)} | <strong>Qty:</strong> ${this.escape(r.quantity)} | <strong>Budget:</strong> ${this.escape(r.budget||"Not listed")}</p><p><strong>Products:</strong> ${r.products.length?r.products.map(p=>`${p.qty}x ${this.escape(p.name)}`).join(", "):"None selected"}</p><p><strong>Total:</strong> ${this.money(r.total||0)}</p><p><strong>Builder:</strong> ${r.builder?Object.entries(r.builder).map(([k,v])=>`${this.escape(k)}: ${this.escape(v)}`).join(" | "):"None"}</p><p><strong>Details:</strong> ${this.escape(r.details||"No extra details")}</p></div>`).join("")}`},
updateRequestStatus(id,status){let req=this.load(DB.requests,[]).map(r=>r.id===id?{...r,status}:r);this.save(DB.requests,req);this.renderAdmin()},
productAdminHtml(){let edit=this.editingProductId?this.products.find(p=>p.id===this.editingProductId):null;return`<h3 style="margin-bottom:12px">${edit?"Edit Product":"Add Product"}</h3><div class="admin-form"><input id="adminName" placeholder="Product Name" value="${this.escapeAttr(edit?.name||"")}"><input id="adminCategory" placeholder="Category" value="${this.escapeAttr(edit?.category||"")}"><input id="adminMarket" placeholder="Market" value="${this.escapeAttr(edit?.market||"")}"><input id="adminUse" placeholder="Use Case" value="${this.escapeAttr(edit?.use||"")}"><input id="adminPrice" type="number" placeholder="Starting Price" value="${edit?.price||""}"><input id="adminEmoji" placeholder="Emoji fallback" value="${this.escapeAttr(edit?.emoji||"")}"><input id="adminRating" type="number" step="0.1" placeholder="Rating" value="${edit?.rating||""}"><input id="adminReviews" type="number" placeholder="Reviews" value="${edit?.reviews||""}"><input id="adminTags" placeholder="Tags comma separated" value="${this.escapeAttr((edit?.tags||[]).join(", "))}"><input id="adminKeywords" placeholder="Search keywords comma separated" value="${this.escapeAttr((edit?.keywords||[]).join(", "))}"><input id="adminImages" class="full" placeholder="Image URLs comma separated" value="${this.escapeAttr((edit?.images||[]).join(", "))}"><textarea id="adminDesc" placeholder="Description">${this.escape(edit?.desc||"")}</textarea><button class="btn primary full" onclick="app.saveAdminProduct()">${edit?"Save Product":"Add Product"}</button>${edit?`<button class="btn full" onclick="app.cancelEdit()">Cancel Edit</button>`:""}</div><h3 style="margin:20px 0 12px">Current Products</h3>${this.products.map(p=>`<div class="admin-product"><strong>${this.escape(p.name)}</strong><p>${this.escape(p.category)} | ${this.money(p.price)} | ${this.escape(p.market)}</p><button class="btn small" onclick="app.openProduct(${p.id})">View</button> <button class="btn small" onclick="app.editProduct(${p.id})">Edit</button> <button class="btn small" onclick="app.deleteProduct(${p.id})">Delete</button></div>`).join("")}`},
saveAdminProduct(){let name=adminName.value.trim();if(!name){alert("Product name is required.");return}let p={id:this.editingProductId||Date.now(),name,category:adminCategory.value.trim()||"Custom",market:adminMarket.value.trim()||"Custom",use:adminUse.value.trim()||"Brand Display",price:Number(adminPrice.value||0),emoji:adminEmoji.value.trim()||"🎈",rating:Number(adminRating.value||4.7),reviews:Number(adminReviews.value||0),badge:this.editingProductId?(this.products.find(x=>x.id===this.editingProductId)?.badge||"Custom"):"New",size:"Custom",productionDays:45,water:false,newest:Date.now(),desc:adminDesc.value.trim()||"Custom inflatable product.",tags:adminTags.value.split(",").map(x=>x.trim()).filter(Boolean),keywords:adminKeywords.value.split(",").map(x=>x.trim()).filter(Boolean),images:adminImages.value.split(",").map(x=>x.trim()).filter(Boolean)};if(this.editingProductId)this.products=this.products.map(x=>x.id===this.editingProductId?p:x);else this.products.push(p);this.editingProductId=null;this.save(DB.products,this.products);if(!this.categories.includes(p.category)){this.categories.push(p.category);this.save(DB.categories,this.categories)}this.buildFilters();this.renderDepartments();this.renderProducts();this.renderAdmin()},
editProduct(id){this.editingProductId=id;this.renderAdmin();document.getElementById("adminSection").scrollIntoView({behavior:"smooth"})},cancelEdit(){this.editingProductId=null;this.renderAdmin()},
deleteProduct(id){if(!confirm("Delete this product from this browser?"))return;this.products=this.products.filter(p=>p.id!==id);this.quote=this.quote.filter(p=>p.id!==id);this.compare=this.compare.filter(x=>x!==id);this.wishes=this.wishes.filter(x=>x!==id);this.save(DB.products,this.products);this.save(DB.quote,this.quote);this.save(DB.compare,this.compare);this.save(DB.wishes,this.wishes);this.buildFilters();this.renderProducts();this.renderQuote();this.renderAdmin()},
categoryAdminHtml(){return`<div class="admin-form"><input id="newCategory" placeholder="New category name"><button class="btn primary" onclick="app.addCategory()">Add Category</button></div>${this.categories.map(c=>`<div class="category-card"><strong>${this.escape(c)}</strong><p>${this.products.filter(p=>p.category===c).length} products</p><button class="btn small" onclick="app.deleteCategory('${this.escapeAttr(c)}')">Delete Category</button></div>`).join("")}`},
addCategory(){let c=newCategory.value.trim();if(!c)return;if(!this.categories.includes(c))this.categories.push(c);this.save(DB.categories,this.categories);this.buildFilters();this.renderDepartments();this.renderAdmin()},
deleteCategory(c){if(!confirm("Delete category? Products will remain, but filter option will disappear."))return;this.categories=this.categories.filter(x=>x!==c);this.save(DB.categories,this.categories);this.buildFilters();this.renderDepartments();this.renderAdmin()},
clearRequests(){if(confirm("Clear all saved quote requests?")){this.save(DB.requests,[]);this.renderAdmin()}},
toggleWish(id){this.wishes=this.wishes.includes(id)?this.wishes.filter(x=>x!==id):[...this.wishes,id];this.save(DB.wishes,this.wishes);this.renderProducts()},
toggleCompare(id){if(this.compare.includes(id))this.compare=this.compare.filter(x=>x!==id);else{if(this.compare.length>=4){alert("You can compare up to 4 products.");return}this.compare.push(id)}this.save(DB.compare,this.compare);this.updateCounts();this.renderProducts()},
showPanel(type){let panel=document.getElementById("sidePanel"),title=document.getElementById("sidePanelTitle"),body=document.getElementById("sidePanelBody");if(type==="recent"){title.textContent="Recently Viewed";let items=this.recent.map(id=>this.products.find(p=>p.id===id)).filter(Boolean);body.innerHTML=items.length?items.map(p=>`<div class="summary-item"><strong>${this.escape(p.name)}</strong><p>${this.money(p.price)}</p><button class="btn small" onclick="app.openProduct(${p.id})">Open</button></div>`).join(""):"<p>No recently viewed products yet.</p>"}if(type==="compare"){title.textContent="Compare Products";let items=this.compare.map(id=>this.products.find(p=>p.id===id)).filter(Boolean);body.innerHTML=!items.length?"<p>No products added to compare yet.</p>":`<table class="compare-table"><tr><th>Product</th>${items.map(p=>`<td>${this.escape(p.name)}</td>`).join("")}</tr><tr><th>Price</th>${items.map(p=>`<td>${this.money(p.price)}</td>`).join("")}</tr><tr><th>Rating</th>${items.map(p=>`<td>${p.rating}</td>`).join("")}</tr><tr><th>Production</th>${items.map(p=>`<td>${p.productionDays} days</td>`).join("")}</tr><tr><th>Water</th>${items.map(p=>`<td>${p.water?"Yes":"No"}</td>`).join("")}</tr></table><br><button class="btn small dark" onclick="app.clearCompare()">Clear Compare</button>`}panel.classList.add("open")},
closePanel(){document.getElementById("sidePanel").classList.remove("open")},clearCompare(){this.compare=[];this.save(DB.compare,this.compare);this.updateCounts();this.closePanel();this.renderProducts()},
maybeShowLeadPopup(){if(localStorage.getItem("inflatepro_lead_closed_v3"))return;document.getElementById("leadPopup").classList.remove("hidden")},closeLeadPopup(){localStorage.setItem("inflatepro_lead_closed_v3","true");document.getElementById("leadPopup").classList.add("hidden")},saveLead(){let email=leadEmail.value.trim();if(!email){alert("Enter an email.");return}let leads=this.load(DB.leads,[]);leads.push({email,date:new Date().toLocaleString()});this.save(DB.leads,leads);this.closeLeadPopup();alert("Lead saved in browser storage.")},
exportData(){let data={products:this.products,quoteRequests:this.load(DB.requests,[]),leads:this.load(DB.leads,[]),exportedAt:new Date().toISOString()};this.download("inflatepro-export.json",JSON.stringify(data,null,2),"application/json")},
exportRequestsCSV(){let req=this.load(DB.requests,[]);let rows=[["Date","Status","Company","Name","Email","Phone","Buyer Type","Quantity","Budget","Products","Total","Details"]];req.forEach(r=>rows.push([r.date,r.status,r.company,r.name,r.email,r.phone,r.buyerType,r.quantity,r.budget,(r.products||[]).map(p=>`${p.qty}x ${p.name}`).join("; "),r.total,r.details]));let csv=rows.map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");this.download("quote-requests.csv",csv,"text/csv")},
download(name,content,type){let blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)},
updateCounts(){let n=this.quote.reduce((s,p)=>s+(p.qty||1),0);document.getElementById("cartCount").textContent=n;document.getElementById("mobileCartCount").textContent=n;document.getElementById("compareCount").textContent=this.compare.length;document.getElementById("adminLoginText").textContent=this.isAdmin?"Open":"Login"},
scrollToProducts(){document.getElementById("productsSection").scrollIntoView({behavior:"smooth"})},goHome(){window.scrollTo({top:0,behavior:"smooth"})},money(n){return"$"+Number(n||0).toLocaleString()+"+"},escape(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))},escapeAttr(s){return this.escape(s).replaceAll("\n"," ")}
};
window.addEventListener("DOMContentLoaded",()=>app.init());window.addEventListener("click",e=>{if(e.target.id==="productModal")app.closeProduct();if(e.target.id==="loginModal")app.closeLogin();if(e.target.id==="designBuilderModal")app.closeDesignBuilder()});
